import s from './page.module.css';
import { ReactElement } from 'react';
import { Metadata } from 'next';
import { Htag } from '@/app/components/Htag/Htag';

export const metadata: Metadata = {
  title: 'First Next App',
  description: 'Generated by create next app'
};

export default function Home(): ReactElement {
  return (
    <main
      // className={}
    >
      <Htag tag={'h1'}>Hello</Htag>
    </main>
  );
}
